export const INDIAN_STATES = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
];

// Simplified list of major cities for demonstration
// In a production app, this should be fetched from an API or a comprehensive JSON dataset
export const STATE_CITIES = {
    "Andaman and Nicobar Islands": ["Port Blair"],
    "Andhra Pradesh": ["Anantapur", "Guntur", "Kadapa", "Kakinada", "Kurnool", "Nellore", "Rajahmundry", "Tirupati", "Vijayawada", "Visakhapatnam"],
    "Arunachal Pradesh": ["Itanagar", "Naharlagun"],
    "Assam": ["Dibrugarh", "Guwahati", "Jorhat", "Nagaon", "Silchar", "Tezpur", "Tinsukia"],
    "Bihar": ["Arrah", "Begusarai", "Bhagalpur", "Bihar Sharif", "Darbhanga", "Gaya", "Katihar", "Muzaffarpur", "Patna", "Purnia"],
    "Chandigarh": ["Chandigarh"],
    "Chhattisgarh": ["Ambikapur", "Bhilai", "Bilaspur", "Jagdalpur", "Korba", "Raigarh", "Raipur", "Rajnandgaon"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
    "Delhi": ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
    "Goa": ["Mapusa", "Margao", "Panaji", "Ponda", "Vasco da Gama"],
    "Gujarat": ["Ahmedabad", "Anand", "Bhavnagar", "Gandhidham", "Gandhinagar", "Jamnagar", "Junagadh", "Rajkot", "Surat", "Vadodara"],
    "Haryana": ["Ambala", "Faridabad", "Gurugram", "Hisar", "Karnal", "Panchkula", "Panipat", "Rohtak", "Sonipat", "Yamunanagar"],
    "Himachal Pradesh": ["Baddi", "Dharamshala", "Mandi", "Nahan", "Paonta Sahib", "Shimla", "Solan", "Sundarnagar"],
    "Jammu and Kashmir": ["Anantnag", "Jammu", "Srinagar"],
    "Jharkhand": ["Bokaro Steel City", "Deoghar", "Dhanbad", "Giridih", "Hazaribagh", "Jamshedpur", "Medininagar", "Phusro", "Ramgarh", "Ranchi"],
    "Karnataka": ["Ballari", "Belagavi", "Bengaluru", "Davanagere", "Hubballi-Dharwad", "Kalaburagi", "Mangaluru", "Mysuru", "Shivamogga", "Vijayapura"],
    "Kerala": ["Alappuzha", "Kannur", "Kochi", "Kollam", "Kozhikode", "Malappuram", "Manjeri", "Palakkad", "Thiruvananthapuram", "Thrissur"],
    "Ladakh": ["Kargil", "Leh"],
    "Lakshadweep": ["Kavaratti"],
    "Madhya Pradesh": ["Bhopal", "Dewas", "Gwalior", "Indore", "Jabalpur", "Ratlam", "Rewa", "Sagar", "Satna", "Ujjain"],
    "Maharashtra": ["Aurangabad", "Kalyan-Dombivli", "Mumbai", "Nagpur", "Nashik", "Navi Mumbai", "Pune", "Solapur", "Thane", "Vasai-Virar City"],
    "Manipur": ["Imphal"],
    "Meghalaya": ["Shillong", "Tura"],
    "Mizoram": ["Aizawl"],
    "Nagaland": ["Dimapur", "Kohima"],
    "Odisha": ["Balasore", "Baripada", "Berhampur", "Bhadrak", "Bhubaneswar", "Cuttack", "Puri", "Rourkela", "Sambalpur"],
    "Puducherry": ["Karaikal", "Mahe", "Puducherry", "Yanam"],
    "Punjab": ["Amritsar", "Batala", "Bathinda", "Hoshiarpur", "Jalandhar", "Ludhiana", "Moga", "Mohali", "Pathankot", "Patiala"],
    "Rajasthan": ["Ajmer", "Alwar", "Bharatpur", "Bhilwara", "Bikaner", "Jaipur", "Jodhpur", "Kota", "Sikar", "Udaipur"],
    "Sikkim": ["Gangtok"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Erode", "Madurai", "Salem", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tiruppur", "Vellore"],
    "Telangana": ["Adilabad", "Hyderabad", "Karimnagar", "Khammam", "Mahbubnagar", "Nalgonda", "Nizamabad", "Ramagundam", "Suryapet", "Warangal"],
    "Tripura": ["Agartala"],
    "Uttar Pradesh": ["Agra", "Aligarh", "Bareilly", "Ghaziabad", "Kanpur", "Lucknow", "Meerut", "Moradabad", "Prayagraj", "Varanasi"],
    "Uttarakhand": ["Dehradun", "Haldwani", "Haridwar", "Kashipur", "Rishikesh", "Roorkee", "Rudrapur"],
    "West Bengal": ["Asansol", "Baharampur", "Bardhaman", "Durgapur", "Habra", "Kharagpur", "Kolkata", "Malda", "Shantipur", "Siliguri"]
};
